name: transportation_app

description: An app that helps the user book a shuttle to his airport

publish_to: none

version: 1.0.0+2

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  authentication: 
    path: ./packages/authentication
  provider:
  #location: 
  firebase_core:
  cloud_firestore:
  shared_preferences:
  image_picker:
  # font_awesome_flutter:
  qr_flutter:
  flutter_stripe:
  http:
  url_launcher:
  uni_links:
  google_maps_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/cancel.png
    - assets/icons/history.png
    - assets/icons/filter.png
    - assets/icons/time.png
    - assets/icons/clear-filter.png
    - assets/icons/three-dots.png
    - assets/icons/three-lines.png
    - assets/icons/passenger.png
    - assets/icons/check-in.png
    - assets/icons/hand.png
    - assets/icons/backpack.png
    - assets/icons/information.png
    - assets/icons/airline.png
    - assets/icons/check.png
    - assets/icons/flight-date.png
    - assets/icons/cash.png
    - assets/icons/card.png
    - assets/icons/no-data.png
    - assets/icons/payment-method.png
    - assets/icons/company.png
    - assets/icons/price.png
    - assets/icons/passenger-data.png
    - assets/icons/aircraft.png
    - assets/icons/transport-to-airport.png
    - assets/icons/browse-options.png
    - assets/icons/fill-data.png
    - assets/icons/order-confirmed.png
    - assets/icons/ticket.png
    - assets/icons/public.png
    - assets/icons/private.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700